### Get all books (unauthorized)
GET http://localhost:3000/books HTTP/1.1

### Get all books (authorized normal)
GET http://localhost:3000/books HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NSwidXNlcm5hbWUiOiJwaW5jb3BhbGxpbm8iLCJyb2xlIjoibm9ybWFsIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjo0MiwiaWF0IjoxNzI2MTI5NzkyLCJleHAiOjE3MjYxMzMzOTJ9LCJpYXQiOjE3MjYxMjk3OTJ9.5GQzp54NYR5PPdH9ncQoKs0FLxERXO1GXRq9muZFsvc

### Get all books (authorized admin)
GET http://localhost:3000/books HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

### Get books with filters
GET http://localhost:3000/books?author=new%20author&published_year=2024 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NSwidXNlcm5hbWUiOiJwaW5jb3BhbGxpbm8iLCJyb2xlIjoibm9ybWFsIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjo0MiwiaWF0IjoxNzI2MTI5NzkyLCJleHAiOjE3MjYxMzMzOTJ9LCJpYXQiOjE3MjYxMjk3OTJ9.5GQzp54NYR5PPdH9ncQoKs0FLxERXO1GXRq9muZFsvc

### Get books with filters and sort
GET http://localhost:3000/books?author=new%20author&sort=asc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

### Get books with pagination
GET http://localhost:3000/books?page=2&limit=12 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

### Get books with filters and pagination
GET http://localhost:3000/books?author=new%20author&published_year=2024&page=1&limit=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

### Get book by id
GET http://localhost:3000/books/34 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

### Create book
POST http://localhost:3000/books HTTP/1.1
content-type: application/json
# normal:
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NSwidXNlcm5hbWUiOiJwaW5jb3BhbGxpbm8iLCJyb2xlIjoibm9ybWFsIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjo0MiwiaWF0IjoxNzI2MTI5NzkyLCJleHAiOjE3MjYxMzMzOTJ9LCJpYXQiOjE3MjYxMjk3OTJ9.5GQzp54NYR5PPdH9ncQoKs0FLxERXO1GXRq9muZFsvc
# admin:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

{
    "title": "altra prova",
    "author": "autore",
    "isbn": "9783161484100",
    "published_year": 1999
}

### Modify book
PUT http://localhost:3000/books/34 HTTP/1.1
content-type: application/json
# normal:
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NSwidXNlcm5hbWUiOiJwaW5jb3BhbGxpbm8iLCJyb2xlIjoibm9ybWFsIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjo0MiwiaWF0IjoxNzI2MTI5NzkyLCJleHAiOjE3MjYxMzMzOTJ9LCJpYXQiOjE3MjYxMjk3OTJ9.5GQzp54NYR5PPdH9ncQoKs0FLxERXO1GXRq9muZFsvc
# admin:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94

{
    "title": "titolo cambiato",
    "author": "nuovo autore",
    "isbn": "4242424242",
    "published_year": 1998
}

### Delete book
DELETE http://localhost:3000/books/35 HTTP/1.1
# normal:
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NSwidXNlcm5hbWUiOiJwaW5jb3BhbGxpbm8iLCJyb2xlIjoibm9ybWFsIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDozMDAwIiwiYXVkIjo0MiwiaWF0IjoxNzI2MTI5NzkyLCJleHAiOjE3MjYxMzMzOTJ9LCJpYXQiOjE3MjYxMjk3OTJ9.5GQzp54NYR5PPdH9ncQoKs0FLxERXO1GXRq9muZFsvc
# admin:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7InN1YiI6NCwidXNlcm5hbWUiOiJzdXBlcnVzZXIiLCJyb2xlIjoiYWRtaW4iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJhdWQiOjQyLCJpYXQiOjE3MjYxMjcxNjIsImV4cCI6MTcyNjEzMDc2Mn0sImlhdCI6MTcyNjEyNzE2Mn0.OqnADtRh3_NmbIXt_qm6A8txHcjA73B7F0Dd7ysjD94
